### ISSUE TITLE
question about IIB implementation

### ISSUE THREAD

**Issue by vaskovasilev** [zheng-wang/irontest#10]
Hello dear Zheng, 
this is not an issue, i just want to ask you something.
when using SSL for IntegrationNodeConnectionParameters, i have an error:

":"Error: com.ibm.broker.config.proxy.ConfigManagerProxyLoggedException: Could not establish remote connection to target integration node (localhost:4443) as user \u0027test\u0027. HTTP error code was 0"

without ssl, all is fine.
did you had such problem before and do you know what might be the problem.

thank you

**Comment by zheng-wang** [comment]
Hi vaskovasilev, thanks for the question.

To enable Iron Test to connect to an IIB 10 integration node through IIB Endpoint (effectively IntegrationNodeConnectionParameters) with SSL, need to add a java trust store under <IronTest_Home>. The trust store must contain the certificate from the integration node web console.

The trust store name and password are configured in the config.yml, like below
```
sslTrustStorePath: ./truststore.jks
sslTrustStorePassword: truststorepass
```

You can have a try on this if interested.

I will try to find some time in future to create some documentation for this, but currently too busy to do it.

**Comment by vaskovasilev** [comment]
Hi Zheng,
thank you for the hint! 
all is fine.

good luck and a lot of success :)

**Comment by zheng-wang** [comment]
[Doc](https://github.com/zheng-wang/irontest/wiki/Configure-Iron-Test-to-be-an-SSL-Client) is created.
