### ISSUE TITLE
Is it possible to call Iron test from Jenkins?

### ISSUE THREAD

**Issue by sooraj2589** [zheng-wang/irontest#11]
How to call iron test from Jenkins?. There is no direct plugin available in Jenkins for Iron test.

**Comment by zheng-wang** [comment]
Right, it is a feature yet to be developed. If you don't want to wait long time, contribution is more than welcome. : )

**Comment by sooraj2589** [comment]
Okay. Thank you for the update. I am looking to call using API, that you mentioned in one of the closed issue
