### ISSUE TITLE
Connecting to a multi-instance queue manager or integration server [query] [feature-request]

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#15]
Can IronTest connect to a multi-instance integration server or queue manager? The settings for the client connection seem to indicate not, as they ask for a single IP address and port. Is it possible to use a connection string with comma-separated connection details, rather than just a single address?

**Comment by zheng-wang** [comment]
Iron Test does not support connecting to multi-instance integration node or queue manager at this moment.

Normally people use a load balancer in front of the active and standby integration nodes or queue managers. If you don't have a load balancer for Iron Test to connect to, I would suggest you not to bother with multi-instance. Automated testing of IIB message flows is normally around the functionality of the message flows. The testing can be done in an environment with a single integration node and a single queue manager which is much simpler comparing to a multi-instance environment. I would suggest you to set up such a single instance environment for testing purpose, to simply your testing requirements. 

On the other hand, Iron Test is a testing tool, and it is not designed to be too complex (covering all environment types). Complex/uncommon testing requirements might be able to be addressed some time in future when a Script Step feature is added to Iron Test for user to write custom code.
