### ISSUE TITLE
XML Schema Validation [feature-request]

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#16]
It would be helpful if an available assertion was to assert that the xml generated is valid against a specified xsd schema

**Comment by zheng-wang** [comment]
Thanks for raising another feature request. : )

My personal experience is that the [XMLEqualAssertion](https://github.com/zheng-wang/irontest/wiki/Assertions#xmlequal-assertion) with the help of placeholder is a more strict type of assertion than XSD validation. With XSD validation, you can only validate the syntax of the XML, while with XMLEqualAssertion (and placeholder), you can validate the data in the XML as well as syntax.

I guess XSD validation is used when you don't care about the data in the XML, and only want to do some kind of smoke testing of the API under test. You want to create quick and simple test case to achieve this, without the need/effort to figure out the expected data in the XML. Please let me know if this is the case.

**Comment by simonalexander2005** [comment]
> Thanks for raising another feature request. : )

You're welcome! I really like your product and it almost does all the things we need for our testing

> My personal experience is that the [XMLEqualAssertion](https://github.com/zheng-wang/irontest/wiki/Assertions#xmlequal-assertion) with the help of placeholder is a more strict type of assertion than XSD validation. With XSD validation, you can only validate the syntax of the XML, while with XMLEqualAssertion (and placeholder), you can validate the data in the XML as well as syntax.
> I guess XSD validation is used when you don't care about the data in the XML, and only want to do some kind of smoke testing of the API under test. You want to create quick and simple test case to achieve this, without the need/effort to figure out the expected data in the XML. Please let me know if this is the case.

I would want to do both, actually - the message flow should output the XML in the correct format according to the schema, and then the fields I care about should have the correct values inside it (which, as you say, is a stricter validation than the schema provides). Some fields I don't care about, as long as they conform to the schema (for example, date-time fields which are generated depending on when the test is run). For one or two fields I could see myself just excluding those fields using placeholders, but for a more complex schema it seems unnecessary when I can just check with XPath for the few things I want to check, then just check that the rest of the message is valid and leave it at that.

 Schemas contain more than just content validation - they enforce things like minOccurs/maxOccurs, sequences, etc. I would want to put through multiple input messages and check it was dealing with those kind of things correctly, but only need to check the business content of the message the first time through - the other times I only care about the message flow generating a message that is valid according to the schema, because I already know it takes care of the business side of the transformation. 

Does that make sense? I'm happy to have a discussion on this if you have a better way in mind.

**Comment by zheng-wang** [comment]
Ok, will find some time to implement this feature.

**Comment by zheng-wang** [comment]
Thanks for raising the request. This feature has been implemented in version [v0.13.0](https://github.com/zheng-wang/irontest/releases/tag/v0.13.0).
