### ISSUE TITLE
Changing from managed endpoint to unmanaged

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#17]
When I create a test step, and set the endpoint to managed, there isn't then an option to go back to being unmanaged again; without deleting and recreating the whole test step

**Comment by zheng-wang** [comment]
It looks intuitive to have the flexibility to change managed back to unmanaged, but personally I don't have a real use of this flexibility. Do you mind sharing your usage scenario?

**Comment by simonalexander2005** [comment]
If I'm copy and pasting a test case that uses a managed endpoint, but want to change the endpoint used in the test case to a different one that I don't want in the list of managed endpoints, perhaps because I'm only going to use it once or it's a temporary change

**Comment by zheng-wang** [comment]
Ok thanks. Will implement it.

**Comment by zheng-wang** [comment]
This request has been implemented in version v0.16.3.
