### ISSUE TITLE
Assertions for an MQ Message dequeue action should allow for non-xml and non-json elements

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#18]
Currently when dequeuing a message from an MQ queue, the only assertions available are XML and JSON - there's no plaintext assertion available for checking the contents of a message that isn't in XML or JSON format

**Comment by zheng-wang** [comment]
This feels like a common requirement. Will implement it, assuming string.equal is what you want to assert.

**Comment by simonalexander2005** [comment]
Yes, that's a good start; but Substring and Contains options would be good too - or even just use a Regex comparer with Java's Pattern class, for example

**Comment by zheng-wang** [comment]
Will do Equal, Contains and Regex. Let me know if Substring is used very often in your work and whether it deserves a separate assertion, given the Regex can cover it.

**Comment by simonalexander2005** [comment]
> Will do Equal, Contains and Regex. Let me know if Substring is used very often in your work and whether it deserves a separate assertion, given the Regex can cover it.

Quite often I have messages that are just strings, and I need to be able to verify that characters 1..5 are a certain string, characters 6..9 are a certain string, etc. It would be possible with regex, but more clean and readable using a specific substring screen I think.

**Comment by zheng-wang** [comment]
Ok will do Substring also then.

**Comment by zheng-wang** [comment]
Thanks for raising the request. The new assertions have been implemented in version [v0.13.0](https://github.com/zheng-wang/irontest/releases/tag/v0.13.0).
