### ISSUE TITLE
Allow Wait Time to be configurable with data table items

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#19]
I want to be able to add a data table entry containing the wait time in milliseconds, and then use ${WAIT_TIME} in the Wait step. This is because some tests of the same message flow with different data are expected to take longer than others, and so this would save having different test cases for different wait times.

Alternatively (or perhaps as well), it would be useful to be able to configure a step that runs just once per test, before each of the individual data table entries; and a step that runs just once afterwards. This would be used for things like initialising caches, putting the test environment back to a stable state, etc.

**Comment by zheng-wang** [comment]
Will do the ${WAIT_TIME} in the Wait step.

The alternative approach (common setup/teardown for data driven test case) seems a significant change. Can discuss it in separate issue if really required.

**Comment by zheng-wang** [comment]
Thanks for raising the request. This improvement has been implemented in version [v0.13.0](https://github.com/zheng-wang/irontest/releases/tag/v0.13.0).
