### ISSUE TITLE
Starting/Stopping an IIB9 message flow

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#22]
If I create an IIB test step, and try and connect to an IIB 9 broker, I get the following error in the logs:

> ERROR [2020-04-15 10:58:51,650] io.irontest.core.runner.DataDrivenTestcaseRunner: null
> ! java.lang.ClassNotFoundException: com.ibm.broker.config.proxy.IntegrationNodeConnectionParameters
> ! at java.net.URLClassLoader.findClass(Unknown Source)
> ! at java.lang.ClassLoader.loadClass(Unknown Source)
> ! at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> ! at java.lang.ClassLoader.loadClass(Unknown Source)
> ! at io.irontest.core.runner.IIBTeststepRunnerClassLoader.loadClass(IIBTeststepRunnerClassLoader.java:52)
> ! at java.lang.ClassLoader.loadClass(Unknown Source)
> ! at java.lang.Class.forName0(Native Method)
> ! at java.lang.Class.forName(Unknown Source)
> ! at io.irontest.core.runner.IIB100TeststepRunner.<init>(IIB100TeststepRunner.java:39)
> ! ... 72 common frames omitted
> ! Causing: java.lang.reflect.InvocationTargetException: null
> ! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> ! at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> ! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> ! at java.lang.reflect.Constructor.newInstance(Unknown Source)
> ! at io.irontest.core.runner.IIBTeststepRunner.run(IIBTeststepRunner.java:52)
> ! at io.irontest.core.runner.TeststepRunner.run(TeststepRunner.java:31)
> ! at io.irontest.core.runner.TestcaseRunner.runTeststep(TestcaseRunner.java:150)
> ! at io.irontest.core.runner.DataDrivenTestcaseRunner.run(DataDrivenTestcaseRunner.java:62)
> ! at io.irontest.resources.TestcaseRunResource.create(TestcaseRunResource.java:50)
> ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ! at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> ! at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> ! at java.lang.reflect.Method.invoke(Unknown Source)
> ! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
> ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
> ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
> ! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
> ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
> ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
> ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
> ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
> ! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
> ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
> ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
> ! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> ! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> ! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
> ! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
> ! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
> ! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
> ! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
> ! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
> ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
> ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
> ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
> ! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
> ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
> ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
> ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
> ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
> ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
> ! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
> ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
> ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
> ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
> ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
> ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
> ! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
> ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
> ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
> ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> ! at org.eclipse.jetty.server.Server.handle(Server.java:531)
> ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
> ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
> ! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
> ! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
> ! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
> ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> ! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
> ! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
> ! at java.lang.Thread.run(Unknown Source)

Looking at the code (https://github.com/zheng-wang/irontest/blob/658d26417d455640c5ca6e41fe7244eac125f24f/irontest-iib/src/main/java/io/irontest/core/runner/IIBTeststepRunner.java), it seems that the IIB test step is always associated with IIB 10.

In that case, how do I create an IIB 9 test step?

**Comment by zheng-wang** [comment]
To create an IIB 9 test step, on the Endpoints tab of the IIB step, just select MQ as Endpoint Type.
