### ISSUE TITLE
Upgrading from 0.13 to 0.14

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#26]
What are the steps for upgrading from 0.13 to 0,14?

If I just copy the database over, I don't see the new FTP steps; and I get an error when I try to create a test step:

> There was an error processing your request. It has been logged (ID 5ad0b49b19cc00c3).
> 
> Details: org.h2.jdbc.JdbcSQLException: Column "API_REQUEST" not found; SQL statement: /* TeststepDAO._insertWithoutName */ insert into teststep (testcase_id, sequence, type, request, api_request, endpoint_id, other_properties) values (?, (select coalesce(max(sequence), 0) + 1 from teststep where testcase_id = ?), ?, ?, ?, ?, ?) [42122-196] [statement:"insert into teststep (testcase_id, sequence, type, request, api_request, endpoint_id, other_properties) values (:t.testcaseId, (select coalesce(max(sequence), 0) + 1 from teststep where testcase_id = :t.testcaseId), :t.type, :request, :apiRequest, :endpointId, :otherProperties)", rewritten:"/* TeststepDAO._insertWithoutName */ insert into teststep (testcase_id, sequence, type, request, api_request, endpoint_id, other_properties) values (:t.testcaseId, (select coalesce(max(sequence), 0) + 1 from teststep where testcase_id = :t.testcaseId), :t.type, :request, :apiRequest, :endpointId, :otherProperties)", parsed:"ParsedSql{sql='/* TeststepDAO._insertWithoutName */ insert into teststep (testcase_id, sequence, type, request, api_request, endpoint_id, other_properties) values (?, (select coalesce(max(sequence), 0) + 1 from teststep where testcase_id = ?), ?, ?, ?, ?, ?)', parameters=ParsedParameters{positional=false, parameterNames=[t.testcaseId, t.testcaseId, t.type, request, apiRequest, endpointId, otherProperties]}}", arguments:{ positional:{1:NULL,2:85,3:{"httpHeaders":[]},4:{"minClassName":".APIRequest"}}, named:{request:NULL,apiRequest:{"minClassName":".APIRequest"},endpointId:85,otherProperties:{"httpHeaders":[]}}, finder:[{lazy bean property arguments "io.irontest.models.teststep.Teststep@268016"]}]

**Comment by zheng-wang** [comment]
Please follow the migration steps [here](https://github.com/zheng-wang/irontest/releases/tag/v0.14.0).

I am thinking of automating some of the migration steps so that it becomes simple for everyone.

**Comment by simonalexander2005** [comment]
Thanks! Is test.mv.db the only file I need to backup, or do I need to keep it in sync with test.trace.db? What about the sample.*.db files?

**Comment by zheng-wang** [comment]
For simplicity, just backup the entire <IronTest_Home>/database folder, so that you don't need to think too much.

But actually, only the test.mv.db needs backup if you haven't played with the sample Article APIs bundled with Iron Test or you can lose the sample Article records you created.

**Comment by zheng-wang** [comment]
Assuming no problem.
