### ISSUE TITLE
Add a custom timeout to IIB "Wait for Processing Completion" step

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#27]
As far as I can see from the code, there is a 30-second timeout on an IIB "Wait for Processing Completion" step.

Could this be made configurable? For example, I have a flow that can take a minute to complete; or I might want the test to fail if the flow processing takes longer than 5 seconds

**Comment by zheng-wang** [comment]
Ok, will do it.

**Comment by zheng-wang** [comment]
This has been implemented in v0.16.0.
