### ISSUE TITLE
Copying a test case with an FTP test step with text in produces an error

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#28]
The following steps can be taken to reproduce the error:

1. Create a new Test Case
2. Create an FTP Test Step
3. Action -> File From -> Text
4. Enter some text into the text box
5. Copy the Test Case, and Paste it
6. Go to the FTP Test Step in the copied Test Case

"File From" will now be blank. Selecting "Text" or "File" gives the following exception each time:

> There was an error processing your request. It has been logged (ID 1949193b34d35b62).
> 
> Details: Missing type id when trying to resolve subtype of [simple type, class io.irontest.models.teststep.APIRequest]: missing type id property 'minClassName' (for POJO property 'apiRequest') at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 415] (through reference chain: io.irontest.models.teststep.Teststep["apiRequest"])

**Comment by zheng-wang** [comment]
Thanks for picking this up. It will be fixed in the next release.

**Comment by zheng-wang** [comment]
Fixed in v0.15.0.
