### ISSUE TITLE
FTP File Text doesn't use properties

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#29]
If I create an FTP step and put ${FILE_CONTENT} into the file content text field, the file will contain the literal string ${FILE_CONTENT}; whereas I would expect it to translate that into the property value

**Comment by zheng-wang** [comment]
Thanks for picking this up. Property will be enabled in the ftp text field in the next release.

**Comment by zheng-wang** [comment]
Fixed in v0.15.0.
