### ISSUE TITLE
IIB10 support

### ISSUE THREAD

**Issue by kimlood** [zheng-wang/irontest#3]
In the setup section for IIB, there is a dependencies for the old jar files: "ConfigManagerProxy.jar" and "ibmjsseprovider2.jar", does irontest work with the new IntegrationAPI.jar? 

mvn install:install-file -Dfile="<IIB_Home>/classes/ConfigManagerProxy.jar" -DgroupId=com.ibm -DartifactId=ConfigManagerProxy -Dversion=<IIB_Version> -Dpackaging=jar
mvn install:install-file -Dfile="<IIB_Home>/jre17/lib/ibmjsseprovider2.jar" -DgroupId=com.ibm -DartifactId=ibmjsseprovider2 -Dversion=<IIB_Version> -Dpackaging=jar

**Comment by zheng-wang** [comment]
Well, this is a very good question. I haven't tried. :)
I guess it could work with IIB10, as I think IBM does well on API backward compatibility.
But if you could have a try and let me know that would be great.

Suppose you are using IIB 10.0.0.0

Modify the irontest-mqiib/pom.xml by 
- replacing <iib.version>[9.0.0.3, 9.0.0.6]</iib.version> with <iib.version>[9.0.0.3, 10.0.0.0]</iib.version>
- replacing the two IIB \<dependency>s with below
        \<dependency>
        &nbsp;&nbsp;\<groupId>com.ibm\</groupId>
        &nbsp;&nbsp;\<artifactId>IntegrationAPI\</artifactId>
        &nbsp;&nbsp;\<version>${iib.version}\</version>
        \</dependency>

Replace the two mvn install:install-file commands you mentioned with below
mvn install:install-file -Dfile="<Filepath_of_IntegrationAPI_Jar>" -DgroupId=com.ibm -DartifactId=IntegrationAPI -Dversion=10.0.0.0 -Dpackaging=jar

Other instructions should be the same as seen on the [wiki page](https://github.com/zheng-wang/irontest/wiki/Build-Iron-Test-with-MQ-IIB-Testing-Features).

**Comment by kimlood** [comment]
Yes, of course I will try this! 
I have changed the dependencies and tweaked the versions a bit. Irontest now seems to be installed and ready, tonight I will try to do a simple test run..

**Comment by kimlood** [comment]
Since the release of IIB10 there is no longer a dependencies to have an IBM MQ installation. So there is some work that needs to be done in order to connect to the broker. 
I do not have time to look into it right now, so I will close this..

**Comment by zheng-wang** [comment]
Thanks for letting me know. I'll add a notice to the [wiki page](https://github.com/zheng-wang/irontest/wiki/Build-Iron-Test-with-MQ-IIB-Testing-Features).

**Comment by zheng-wang** [comment]
IIB 10 support has been added since v0.5.8. The build process has been simplified.
