### ISSUE TITLE
Change IIB Endpoint Type after selecting a managed endpoint

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#31]
I have recently upgraded from IIB9 to IIB10; and as such need to update all my tests accordingly.

If I open an IIB test step and try to change the endpoint details, I can only select another "MQ" type endpoint, instead of being able to change it to an IIB-type endpoint.

**Comment by zheng-wang** [comment]
Thanks for raising this. A better way to address the issue might be to use some automated script or Java code to upgrade all IIB 9 endpoints to IIB 10 in one go. 

Especially, IIB 9 has been discontinued for quite some time, and I have been thinking about removing it's support from Iron Test. Switching between 9 and 10 on UI would then be a temp feature.

I have some higher priority features to develop so not sure when will have time to create the auto migration for IIB endpoints. If you are interested, might have a try at this moment.

**Comment by simonalexander2005** [comment]
yeah fair enough, a script to do it would be enough.

**Comment by zheng-wang** [comment]
IIB v9 support has been removed since API Test Base v0.18.3. Upgrade instructions can be found in the [release notes](https://github.com/apitestbase/apitestbase/releases).
