### ISSUE TITLE
Error during the build

### ISSUE THREAD

**Issue by sakinalanaveen** [zheng-wang/irontest#4]
[ERROR] Failed to execute goal on project irontest-assembly: Could not resolve d
ependencies for project io.irontest:irontest-assembly:jar:0.6.1: Failed to colle
ct dependencies at io.irontest:irontest-mq:jar:0.6.1: Failed to read artifact de
scriptor for io.irontest:irontest-mq:jar:0.6.1: Could not transfer artifact io.i
rontest:irontest-mq:pom:0.6.1 from/to irontest-mvn-repo (https://raw.github.com/
zheng-wang/irontest/mvn-repo/): sun.security.validator.ValidatorException: PKIX
path building failed: sun.security.provider.certpath.SunCertPathBuilderException
: unable to find valid certification path to requested target

**Comment by zheng-wang** [comment]
Can you please let me know the output you get when running command 'mvn --version'?

**Comment by sakinalanaveen** [comment]
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:4
7-05:00)
Maven home: C:\Sakinala\Software\maven\maven
Java version: 9.0.1, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-9.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by zheng-wang** [comment]
I was able to build with exactly same Maven and Java version as yours. So not too sure what caused the 'unable to find valid certification path to requested target' error.

However, even if I could build, I could not run the jar with Java 9. Need some investigation. So for now please use Java 8 to build and run. To use Maven with JDK 8, set environment variable JAVA_HOME=<JDK8_Install_Path>.

If you still see the same error during build, and your machine is behind a firewall, try using a proxy server in C:\Users\<user>\.m2\settings.xml (create it if not exist). If not working, could further try
https://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs
https://stackoverflow.com/questions/25911623/problems-using-maven-and-ssl-behind-proxy/25912982#25912982
