### ISSUE TITLE
Artifact error

### ISSUE THREAD

**Issue by raz197** [zheng-wang/irontest#5]
I'm following the instructions from the wiki page and have downloaded the latest v0.7.2, extracted it to a folder and when running 

`mvn clean package -pl irontest-assembly -am -P prod`

I'm getting the following error: 

**_Failed to execute goal on project irontest-assembly: Could not resolve dependencies for project io.irontest:irontest-assembly:jar:0.7.2: Failed to collect dependencies at io.irontest:irontest-mq:jar:0.7.2: Failed to read artifact descriptor for io.irontest:irontest-mq:jar:0.7.2: Could not transfer artifact io.irontest:irontest-mq:pom:0.7.2 from/to irontest-mvn-repo (https://raw.github.com/zheng-wang/irontest/mvn-repo/)_**

If I attempt to access https://raw.github.com/zheng-wang/irontest/mvn-repo/ directyl, I get a 400: Invalid request error 

Maven and JDK installed are:

`mvn -version`

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T05:39:06+10:00)
Maven home: C:\Program Files\Apache\apache-maven-3.5.0\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_121\jre
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Can you please help?

**Comment by zheng-wang** [comment]
Try this. Locate irontest-assembly/pom.xml in the downloaded release, and in it replace `https://raw.github.com/zheng-wang/irontest/mvn-repo/` with `https://github.com/zheng-wang/irontest/raw/mvn-repo/`. Rerun the build command. 

Let me know if it works.

**Comment by raz197** [comment]
Replacing the line gives the following error:

**_Failed to execute goal on project irontest-assembly: Could not resolve dependencies for project io.irontest:irontest-assembly:jar:0.7.2: Failed to collect dependencies at io.irontest:irontest-mq:jar:0.7.2: Failed to read artifact descriptor for io.irontest:irontest-mq:jar:0.7.2: Could not transfer artifact io.irontest:irontest-mq:pom:0.7.2 from/to irontest-mvn-repo (https://github.com/zheng-wang/irontest/raw/mvn-repo/)_**

If i access https://github.com/zheng-wang/irontest/raw/mvn-repo/ in a browser, it gives Page not found 404 error.

**Comment by zheng-wang** [comment]
Actually either URL is not accessible directly, as GitHub does not provide corresponding HTTPS service. The URL is used as a base for constructing file URLs for downloading, for example https://raw.github.com/zheng-wang/irontest/mvn-repo/io/irontest/irontest-mq/0.7.2/irontest-mq-0.7.2.pom. mvn-repo is a branch of the source code which you can navigate in browser like the master branch.

We need more information about the build failure. Would you be able to revert the change to the pom.xml and run below command and attach the generated build.log to this issue?

    mvn clean package -pl irontest-assembly -am -P prod -X > build.log

What we need to know is why https://raw.github.com/zheng-wang/irontest/mvn-repo/io/irontest/irontest-mq/0.7.2/irontest-mq-0.7.2.pom can not be downloaded by Maven.

**Comment by raz197** [comment]
Issues was with my internet connection/proxy

I connected to another internet connection and it downloaded all the files, i was able to fire up the server and created a SOAP test. Worked great.

Off to set it up for MQ Server now. 

Thanks heaps for your help, I'll ask more questions as I work my way through but congratulations on creating this simple and effective solution, well done!!!

**Comment by zheng-wang** [comment]
Cool and happy to see you get started. Let me know if you have any other questions.

**Comment by zheng-wang** [comment]
Proxy issue should no longer exist, as the irontest-iib and irontest-mq artifacts have been hosted in Maven Central.

**Comment by Shiva143153** [comment]
Hi, I'm trying to use the ( IIB step ) in which I've given the Host and rest all details in the Endpoint Details. 
But when I'm trying to give the port no: 8081. Its is popping out in valid port no. 
![Screenshot (36)](https://user-images.githubusercontent.com/48998551/55261900-373f8000-523a-11e9-8478-3d3b46472b57.png)


Is their anyway I can find the solution out of it.

**Comment by zheng-wang** [comment]
Moved the comment to a [new issue](https://github.com/zheng-wang/irontest/issues/6), as it is a different topic.
