### ISSUE TITLE
Invalid port number

### ISSUE THREAD

**Issue by zheng-wang** [zheng-wang/irontest#6]
From @Shiva143153:

Hi, I'm trying to use the ( IIB step ) in which I've given the Host and rest all details in the Endpoint Details.
But when I'm trying to give the port no: 8081. Its is popping out in valid port no.

Is their anyway I can find the solution out of it.

**Comment by zheng-wang** [comment]
There was a port number validation defect. It is fixed and a new release v0.11.1 is published. Please use this new release and let me know if the issue is resolved.

**Comment by Shiva143153** [comment]
Yes! It's working. Thank you.
